project:
  type: book

book:
  title: "Curso: Análisis de Imágenes Satelitales para SII"
  subtitle: "Centro de Inteligencia Territorial - UAI"
  # affiliation-title: "Universidad Adolfo Ibáñez - Chile"
  author: "Denis Berroeta González (denis.berroeta@uai.cl)"
  date: "2023-04-11"
  #number-sections: 3
  page-footer: 
    left: "Copyright 2023, Denis Berroeta" 
  chapters:
    - index.qmd
    - objetivos.qmd
    - fundamentos_PR.qmd
    - satelites_sensores.qmd
    - intro_gee.qmd
    
    - part: "Tareas"
      chapters:
        - tarea_1.qmd
        #- tarea_2.qmd
        
    - references.qmd
        
  appendices:
    - intro_R.qmd
    - variables_R.qmd
    - funciones.qmd
    - loops_R.qmd
    - tidyverse_R.qmd
    - espacial_R.qmd
    - install_rgee.qmd
      #- luces_nocturnas.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
    css: styles/style.css
    fig-align: "center"
    fig-cap-location: "margin"
    tab-cap-location: "left"
    mailto: "denis.berroeta@uai.cl"
  
execute:
  warning: false
  
editor: source
always_allow_html: true



